### ISSUE TITLE
ERROR: the XML

### ISSUE THREAD

**Issue by cimbusch** [jduc/geoDL#1]
python geoDL.py --dry geo GSE13373

################################################################################
               ___  _
  __ _ ___ ___|   \| |
 / _` / -_) _ \ |) | |__
 \__, \___\___/___/|____|
 |___/                   v1.0.b5

################################################################################

Getting correspondance table from GEO...
 > Found 293 samples on GEO page...

Looking for the metadata on ENA website...
http://www.ebi.ac.uk/ena/data/warehouse/search?query=%22geo_accession=%22GSE13373%22%22&result=study&display=xml
 > Visiting ENA website...

 > ERROR: the XML at http://www.ebi.ac.uk/ena/data/warehouse/search?query=%22geo_accession=%22GSE13373%22%22&result=study&display=xml looks weird, probably missing entry!

**Comment by jduc** [comment]
Sorry took forever to answer. Problem comes from ENA website that does not have the metadata table for your GEO. The program depends on that table to download the file, and since it can only find an XLM on ENA, it cannot parse it and crash. I suppose you downloaded the data by other means by now so I'm gonna close this, sorry again for not seeing it before, had not come back to this project for ages.
